name: deepblue
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  permission_handler: ^11.2.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  http: ^1.1.0
  connectivity_plus: ^5.0.2
  image: ^4.1.3
  provider: ^6.0.5
  path: ^1.8.3
  flutter_image_compress: ^2.0.4
  http_parser: ^4.0.2
  share_plus: ^7.0.0
  pdf: ^3.10.4
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  flutter_pdfview: ^1.3.2
  open_file: ^3.3.2
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_logo.png